---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: detect-aws-credentials
    args:
    - --allow-missing-credentials
  - id: detect-private-key
    exclude: .gitleaks.toml|.gitleaks.untouched.toml
  - id: end-of-file-fixer
    exclude: .*\/generated\/.*|values-default\.yml|CHANGELOG\.md|generated_.*
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: pretty-format-json
    args:
    - --autofix
    - --no-sort-keys
    - --indent=2
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.28.0
  hooks:
    - id: yamllint
      args: [-d=relaxed]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: forbid-binary
  - id: shellcheck # Needs shellcheck: https://github.com/koalaman/shellcheck
  - id: shfmt # Needs shfmt: https://github.com/mvdan/sh/releases

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
    - id: forbid-crlf
    - id: remove-crlf

- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.0
  hooks:
    - id: gitleaks
